version: "3.8"

services:
  # mysql container
  standard_mysql:
    image: mysql
    container_name: standard_mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app_web

  # phpmyadmin container
  standard_phpmyadmin:
    image: phpmyadmin
    container_name: standard_phpmyadmin
    restart: always
    depends_on:
      - standard_mysql
    ports:
      - 8060:80
    environment:
      PMA_HOST: standard_mysql
    networks:
      - app_web

  # app apache server container
  app_web:
    build: .
    container_name: app_web
    ports:
      - "8740:80"
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
      - ./omniacrm:/var/www
    restart: always
    networks:
      - app_web

networks:
  app_web:

volumes:
  db-data: